"""empty message

Revision ID: 6b7e995a37d2
Revises: f7607d65421b
Create Date: 2026-02-25 22:28:24.117180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7e995a37d2'
down_revision = 'f7607d65421b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=128), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_employee_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['user'])
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_employee_id_key'), ['employee_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('role')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
